services:
  - type: web
    name: hackathon-backend
    runtime: node
    buildCommand: npm install --production && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=800 --optimize-for-size --gc-interval=100 --max-new-space-size=256
      - key: DATABASE_URL
        sync: false # À définir manuellement
      - key: JWT_SECRET
        sync: false # À définir manuellement
      - key: EMAIL_HOST
        sync: false # Optionnel
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false # Optionnel
      - key: EMAIL_PASS
        sync: false # Optionnel
      - key: PORT
        value: 10000
    healthCheckPath: /health
